name: Convert Markdown to HTML

on:
  push:
    branches:
      - main

jobs:
  converttopdf:
    name: Build HTML
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Convert files
        run: sh convert_md_to_html.sh

      - name: Upload PDF artifacts
        uses: actions/upload-artifact@v4
        with:
          name: output-html
          path: output
