name: Convert Markdown to PDF

on:
  push:
    branches:
      - main
    paths:
      - 'report/**.md'
      - 'report/images/**'

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Convert files
        run: sh convert_md_to_pdf.sh

      - name: Upload PDF artifacts
        uses: actions/upload-artifact@v4
        with:
          name: output-pdfs
          path: output
