name: Convert Markdown to PDF

on:
  push:
    branches:
      - main

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install fontspec
      run: pip install fontspec

    - name: Convert files
      run: sh convert_md_to_pdf.sh

    - name: Upload PDF artifacts
      uses: actions/upload-artifact@v4
      with:
        name: output-pdfs
        path: output
