name: Convert Markdown to PDF

on:
  push:
    branches:
      - main
    paths:
      - 'report/**.md'
      - 'report/images/**'

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: report
          output_dir: pdfs
          images_dir: report/images
          image_import: ./images
          build_html: false
      - uses: actions/upload-artifact@v4
        with:
          name: docs
          path: pdfs
